---
- name: reload caddy
  ansible.builtin.service:
    name: caddy
    state: reloaded
  become: yes
  become_method: sudo

- name: restart program
  community.general.supervisorctl:
    config: /etc/supervisor/supervisord.conf
    name: "{{ item }}"
    state: restarted
  loop:
    - django-dream-blog
    - django-dream-blog-huey
  become: yes
  become_method: sudo
