# Generated by Django 5.2.10 on 2026-02-27 09:47

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FriendLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('modified_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='Modified At')),
                ('site_name', models.CharField(max_length=100, verbose_name='site name')),
                ('site_link', models.URLField(verbose_name='site link')),
                ('rank', models.IntegerField(default=0, verbose_name='rank')),
            ],
            options={
                'verbose_name': 'friend link',
                'verbose_name_plural': 'friend links',
                'ordering': ['rank', 'created_at'],
            },
        ),
    ]
