# Generated by Django 5.0.1 on 2024-01-28 14:21

import django.utils.timezone
import hitcount.models
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Created At",
                    ),
                ),
                (
                    "modified_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Modified At",
                    ),
                ),
                ("content", models.TextField(verbose_name="Content")),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("excerpt", models.TextField(blank=True, verbose_name="Excerpt")),
                (
                    "publish_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Publish Date"
                    ),
                ),
                ("hidden", models.BooleanField(default=False, verbose_name="Hidden")),
                (
                    "comments_enabled",
                    models.BooleanField(default=True, verbose_name="Comments Enabled"),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
            },
            bases=(hitcount.models.HitCountMixin, models.Model),
        ),
    ]
