# Generated by Django 5.0.4 on 2025-07-10 08:41

import markdown_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=markdown_field.fields.MarkdownField(verbose_name='Content'),
        ),
    ]
