---
- name: Ensure staticfiles and media directory
  ansible.builtin.file:
    path: "{{ project_www_path }}"
    owner: "{{ user }}"
    state: directory
  become: yes
  become_method: sudo

- name: Run django management commands
  ansible.builtin.shell:
    cmd: "{{ project_venv_path }}/bin/python manage.py {{ item }} --settings=config.settings.production"
    chdir: "{{ project_path }}"
  loop:
    - collectstatic --noinput
    - migrate
  environment:
    DJANGO_READ_DOT_ENV_FILE: yes
