---
- name: Copy config file
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/supervisor/conf.d/{{ item }}"
  loop:
    - django_dream_blog.conf
    - django_dream_blog_huey.conf
  notify: restart program

- name: Add program
  community.general.supervisorctl:
    config: /etc/supervisor/supervisord.conf
    name: "{{ item }}"
    state: present
  loop:
    - django-dream-blog
    - django-dream-blog-huey
