# Generated by Django 5.0.4 on 2025-07-10 08:41

import markdown_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree_comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treecomment',
            name='comment',
            field=markdown_field.fields.MarkdownField(max_length=3000, verbose_name='comment'),
        ),
    ]
