# Generated by Django 5.0.1 on 2024-01-28 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tutorials", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorial",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
        migrations.AddField(
            model_name="tutorial",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tutorials.category",
                verbose_name="Category",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="tutorial",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tutorials.tutorial",
                verbose_name="Tutorial",
            ),
        ),
    ]
